version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}fieldlevel
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: on-failure